#!/bin/bash

#execute below command only if required
export JAVA_HOME=/Users/tharunk/installations/jdk-17.0.2.jdk/Contents/Home

# http://mywiki.wooledge.org/BashFAQ/028
if [[ $BASH_SOURCE = */* ]]; then
    DIR=${BASH_SOURCE%/*}/
else
    DIR=./
fi
# exec not required since we've add jar executable plugin
exec java -Xmx256M -jar "$DIR/target/whirlpool-1.0-SNAPSHOT-jar-with-dependencies.jar"